### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by leodido** [falcosecurity/client-go#23]
**What would you like to be added**:
Instead of doing releases manually, we want do to them automatically.
Goreleaser does that job very well.

Goreleaser website:
https://goreleaser.com

**Why is this needed**:

Manual releases are a pain

**Comment by fntlnz** [comment]
We can probably get what we did for falcoctl

https://github.com/falcosecurity/falcoctl/pull/30

**Comment by leogr** [comment]
That could be further automated by using the [go-releaser GitHub Action](https://goreleaser.com/actions/). :eyes:

**Comment by leodido** [comment]
We intend to automate the whole release process using the prow (@poiana) bot we have in place, as discussed in the today office hours (here the issue discussed: https://github.com/falcosecurity/community/issues/52).

**Comment by leogr** [comment]
I can work on this
/assign

**Comment by leogr** [comment]
Since [gorelaser won't support libraries](https://github.com/goreleaser/goreleaser/issues/981) and client-go does not contain a `main` function, I guess we have to find an alternative :disappointed:

**Comment by leogr** [comment]
Quick update: next `goreleaser` release will have the support for library project https://github.com/goreleaser/goreleaser/pull/1419

So we can do it :)

Special thanks to @caarlos0 for his support on this
