### ISSUE TITLE
Stub gRPC server

### ISSUE THREAD

**Issue by leodido** [falcosecurity/client-go#35]
**Motivation**

I'd like having tests for this repository.

Thus, we need a stub gRPC server in order to do some state testing. 

**Feature**

Implementing a stub gRPC server: a gRPC server that provides canned answers.

**Alternatives**

A mock gRPC server.

But this requires a bit more effort and I'd postpone it to when we'll want to do behavioral testing.

**Additional context**

None.

**Comment by Issif** [comment]
gRPC team provides nice README and examples to do so : https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md

**Comment by ndhanushkodi** [comment]
I'd like to work on this :) /assign

**Comment by ndhanushkodi** [comment]
I'd like to work on this!
/assign
