### ISSUE TITLE
Move to google.golang.org/protobuf

### ISSUE THREAD

**Issue by nibalizer** [falcosecurity/client-go#48]
**Describe the bug**

Right now we use the v1 of protobufs in go. That is deprecated and we need to move to v2.

https://blog.golang.org/protobuf-apiv2

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leogr** [comment]
I believe we still want this
/remove-lifecycle rotten
