### ISSUE TITLE
Update protos to include latest additions to the gRPC version API

### ISSUE THREAD

**Issue by leodido** [falcosecurity/client-go#49]
**Motivation**

@nibalizer did this [PR](https://github.com/falcosecurity/falco/pull/1507) to add Falco Engine version (and fields checksum) to the version proto.

**Feature**

Add them to this client too.

**Comment by leogr** [comment]
Also, note that https://github.com/falcosecurity/falco/pull/1451 introduced a [small addition](https://github.com/falcosecurity/falco/pull/1451/files#diff-53dd17a76e384bb5e8ee70d7710a3590c426782dc559fd2ce59f063ce62296b2) to the proto.

**Comment by nibalizer** [comment]
The protos are pulled in by Make, but we probably want to push recompiled code to the repo
