### ISSUE TITLE
Volunteer as owner

### ISSUE THREAD

**Issue by krisnova** [falcosecurity/client-go#5]
I would like to volunteer as an owner of this repository. I have a lot of experience writing Go, and would like to be involved with code reviews periodically.

**Comment by leodido** [comment]
Sure! You are listed as owner in the [OWNERS](https://github.com/falcosecurity/client-go/blob/master/OWNERS) file.

**Comment by fntlnz** [comment]
Created the team @falcosecurity/client-go-maintainers  and added you and the others in the owners file. I think we can close this.

/close
