### ISSUE TITLE
Volunteer as owner for client go.

### ISSUE THREAD

**Issue by rajibmitra** [falcosecurity/client-go#6]
Hi Team, 

I would like to volunteer as owner of our client go repository, I have some experience writing go with unit test cases. I would love get involved building this go client. 

Thanks,

**Comment by fntlnz** [comment]
Cool, please do a PR adding yourself yourself under approvers in [OWNERS](https://github.com/falcosecurity/client-go/blob/master/OWNERS) and I'll happily approve it.

**Comment by rajibmitra** [comment]
#9

**Comment by rajibmitra** [comment]
Here its  @fntlnz  #9

**Comment by fntlnz** [comment]
Closed since I thought this was done but it's not, feel free to open the PR again @rajibmitra

**Comment by leodido** [comment]
Hey @rajibmitra could you send the PR with you nickname under the reviewers section of the OWNERS file? :)
